export const international = [
    'Easter',
    'New Year',
    'Valentine',
    'Halloween',
    'Thanksgiving',
    'Christmas',
    'New Year',
    'Valentine',
    'Thanksgiving',
    'Christmas',
    'National Science Day',
    'World Health Day',
    'World Environment Day',
    'World Food Day',
    'World Water Day',
    'World Population Day',
    'World Health Day',
    'Earth Day',
]

export const indian = [
    'Diwali',
    'Holi',
    'Navaratri',
    'Republic Day',
    'Gandhi Jayanti',
    'Republic Day',
    'Independence Day',
    'Mahavir Jayanti',
    'Durga Puja',
    'Ganesh Chaturthi',
    'Maha Shivaratri',
    'Ram Navami',
    'Makar Sankranti',
    'Guru Nanak Jayanti',
    'Krishna Janmashtami',
    'Hanuman Jayanti',
]